Vagrant.configure("2") do |config|
  config.vm.define "ansible-master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "ansible-master"
    master.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "node1" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "node2" do |node|
    node.vm.box = "ubuntu/jammy64"
    node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "192.168.56.12"
  end
end