services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: mariadb:10.7
    container_name: order-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: orderdb
      MARIADB_USER: orderuser
      MARIADB_PASSWORD: orderpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uorderuser", "-porderpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass

  payment-service:
    build: ./payment-service
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      order-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      order-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass

volumes:
  db_data: