spring:
  kafka:
    # Kafka 브로커(서버) 주소 목록 (hostname:port)
    bootstrap-servers: kafka:9092

    consumer:
      # 같은 그룹 아이디를 가진 컨슈머끼리 메시지를 분산 처리할 때 사용
      # spring.profiles.active 프로파일마다 고유한 그룹 아이디를 사용하도록 동적 설정
      group-id: chat-group-${spring.profiles.active}

      # 컨슈머가 처음 시작하거나 오프셋이 없을 때 어디서부터 읽을지 결정
      # earliest: 가장 오래된(처음) 메시지부터 읽기
      auto-offset-reset: earliest

      # 메시지 키를 문자열로 디시리얼라이즈(역직렬화)할 클래스
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 메시지 값을 JSON → 객체로 변환할 디시리얼라이저
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        # JSON 디시리얼라이즈 시 신뢰할 수 있는 패키지 패턴 지정
        # "*" 은 모든 패키지를 허용 (개발 환경에서만 사용 권장)
        spring.json.trusted.packages: "*"

    producer:
      # 메시지 키를 문자열로 직렬화할 클래스
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 메시지 값을 객체 → JSON 문자열로 직렬화할 클래스
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
