services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  chat-app-1:
    build: ./chat-app
    container_name: chat-app-1
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=replica1
    depends_on:
      - kafka

  chat-app-2:
    build: ./chat-app
    container_name: chat-app-2
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=replica2
    depends_on:
      - kafka

  chat-app-3:
    build: ./chat-app
    container_name: chat-app-3
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=replica3
    depends_on:
      - kafka
